'use client';

import { Activity, AlertTriangle, Boxes, CarFront, CircleDollarSign, FolderTree, Plus, RefreshCw, ShoppingCart, Tags, UsersRound } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { money } from '@/lib/api';
import type { Category, Manufacturer, Order, Product, ProductList, User, VehicleMake } from '@/lib/types';
import { useAuth } from './providers/auth-provider';
import { useI18n } from './providers/i18n-provider';

type Dashboard = { metrics: { totalUsers: number; totalProducts: number; totalOrders: number; revenue: number }; recentOrders: Order[]; lowStock: { id: string; sku: string; name: string; manufacturer: string; stockQuantity: number }[] };
type Tab = 'dashboard' | 'products' | 'categories' | 'manufacturers' | 'vehicles' | 'orders' | 'users';

export function AdminContent() {
  const { locale, t } = useI18n();
  const { user, loading, authenticatedFetch } = useAuth();
  const [tab, setTab] = useState<Tab>('dashboard');
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [products, setProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [manufacturers, setManufacturers] = useState<Manufacturer[]>([]);
  const [vehicles, setVehicles] = useState<VehicleMake[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [showProductForm, setShowProductForm] = useState(false);
  const load = useCallback(async () => {
    if (user?.role !== 'ADMIN') return;
    const loc = locale.toUpperCase();
    const [d, p, c, m, v, o, u] = await Promise.all([
      authenticatedFetch<Dashboard>('/admin/dashboard'),
      authenticatedFetch<ProductList>(`/products?locale=${loc}&limit=60`),
      authenticatedFetch<Category[]>(`/categories?locale=${loc}`),
      authenticatedFetch<Manufacturer[]>('/manufacturers'),
      authenticatedFetch<VehicleMake[]>('/vehicles'),
      authenticatedFetch<Order[]>('/orders?limit=50'),
      authenticatedFetch<User[]>('/users?limit=50'),
    ]);
    setDashboard(d); setProducts(p.items); setCategories(c); setManufacturers(m); setVehicles(v); setOrders(o); setUsers(u);
  }, [authenticatedFetch, locale, user?.role]);
  useEffect(() => { if (user?.role === 'ADMIN') void load(); }, [user?.role, load]);
  if (loading) return <div className="container-page py-20"><div className="h-96 animate-pulse rounded-[2rem] bg-ink/5"/></div>;
  if (user?.role !== 'ADMIN') return <div className="container-page py-24"><div className="panel mx-auto max-w-xl p-10 text-center"><AlertTriangle className="mx-auto text-orange" size={42}/><h1 className="mt-5 font-display text-3xl font-bold">{t('admin.access')}</h1></div></div>;
  const tabs: [Tab, string, React.ReactNode][] = [['dashboard','Dashboard',<Activity key="d"/>],['products',t('admin.products'),<Boxes key="p"/>],['categories',t('admin.categories'),<FolderTree key="c"/>],['manufacturers',t('admin.manufacturers'),<Tags key="m"/>],['vehicles',t('admin.vehicles'),<CarFront key="v"/>],['orders',t('admin.orders'),<ShoppingCart key="o"/>],['users',t('admin.users'),<UsersRound key="u"/>]];
  return (
    <div className="container-page py-10">
      <div className="flex flex-col gap-6 border-b border-ink/10 pb-9 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Admin / Operations</p><h1 className="mt-3 font-display text-5xl font-bold">{t('admin.title')}</h1></div><button onClick={() => void load()} className="btn-outline w-fit"><RefreshCw size={16}/>Refresh</button></div>
      <div className="mt-8 flex gap-2 overflow-x-auto pb-3 no-scrollbar">{tabs.map(([id,label,icon]) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-full px-4 py-2.5 text-sm font-bold ${tab === id ? 'bg-ink text-white' : 'border border-ink/10 bg-white'}`}>{icon}{label}</button>)}</div>
      <div className="mt-8">
        {tab === 'dashboard' && dashboard && <DashboardView data={dashboard} locale={locale} t={t}/>}
        {tab === 'products' && <section><AdminHeading title={t('admin.products')} action={<button onClick={() => setShowProductForm(!showProductForm)} className="btn-primary"><Plus size={17}/>New product</button>}/>{showProductForm && <ProductCreateForm categories={categories} manufacturers={manufacturers} vehicles={vehicles} request={authenticatedFetch} onCreated={() => { setShowProductForm(false); void load(); }}/>}<div className="panel mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-ink/10 text-xs uppercase tracking-wider text-steel"><Th>SKU / Product</Th><Th>Maker</Th><Th>Price</Th><Th>Stock</Th><Th/></tr></thead><tbody>{products.map((p) => <tr key={p.id} className="border-b border-ink/5"><Td><b>{p.name}</b><small className="block text-steel">{p.sku}</small></Td><Td>{p.manufacturer.name}</Td><Td>{money(p.price, locale)}</Td><Td><b className={p.stockQuantity <= 5 ? 'text-orange' : ''}>{p.stockQuantity}</b></Td><Td><div className="flex gap-3"><button onClick={async () => { const price=window.prompt('New price',String(p.price)); const stock=window.prompt('New stock quantity',String(p.stockQuantity)); if (price && stock) { await authenticatedFetch(`/products/${p.id}`, { method: 'PATCH', body: JSON.stringify({ price:Number(price), stockQuantity:Number(stock) }) }); void load(); } }} className="text-xs font-bold text-blue-700">Edit</button><button onClick={async () => { await authenticatedFetch(`/products/${p.id}`, { method: 'DELETE' }); void load(); }} className="text-xs font-bold text-red-600">Deactivate</button></div></Td></tr>)}</tbody></table></div></section>}
        {tab === 'categories' && <EntitySection title={t('admin.categories')} form={<CategoryForm request={authenticatedFetch} onCreated={() => void load()}/>}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map((x) => <div key={x.id} className="panel p-5"><span className="text-2xl">{x.icon}</span><b className="ml-3">{x.name}</b><p className="mt-3 text-sm text-steel">{x._count.products} products · /{x.slug}</p><button onClick={async()=>{await authenticatedFetch(`/categories/${x.id}`,{method:'DELETE'});void load();}} className="mt-3 text-xs font-bold text-red-600">Deactivate</button></div>)}</div></EntitySection>}
        {tab === 'manufacturers' && <EntitySection title={t('admin.manufacturers')} form={<ManufacturerForm request={authenticatedFetch} onCreated={() => void load()}/>}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{manufacturers.map((x) => <div key={x.id} className="panel p-5"><b>{x.name}</b><p className="mt-2 text-sm text-steel">{x._count.products} products</p><button onClick={async()=>{await authenticatedFetch(`/manufacturers/${x.id}`,{method:'DELETE'});void load();}} className="mt-3 text-xs font-bold text-red-600">Deactivate</button></div>)}</div></EntitySection>}
        {tab === 'vehicles' && <EntitySection title={t('admin.vehicles')} form={<VehicleMakeForm request={authenticatedFetch} onCreated={() => void load()}/>}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{vehicles.map((make) => <div key={make.id} className="panel p-6"><h3 className="font-display text-2xl font-bold">{make.name}</h3>{make.models.map((model) => <div key={model.id} className="mt-4 rounded-2xl bg-fog p-4"><b>{model.name}</b>{model.engines.map((engine) => <p key={engine.id} className="mt-2 text-sm text-steel">{engine.name} · {engine.fuelType} · {engine.powerHp} hp</p>)}</div>)}</div>)}</div></EntitySection>}
        {tab === 'orders' && <section><AdminHeading title={t('admin.orders')}/><OrdersTable orders={orders} locale={locale} request={authenticatedFetch} reload={load} t={t}/></section>}
        {tab === 'users' && <section><AdminHeading title={t('admin.users')}/><div className="panel mt-6 overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-ink/10"><Th>User</Th><Th>Email</Th><Th>Role</Th><Th>Status</Th></tr></thead><tbody>{users.map((u) => <tr key={u.id} className="border-b border-ink/5"><Td><b>{u.firstName} {u.lastName}</b></Td><Td>{u.email}</Td><Td>{u.role}</Td><Td><span className="text-emerald-600">● Active</span></Td></tr>)}</tbody></table></div></section>}
      </div>
    </div>
  );
}

function DashboardView({ data, locale, t }: { data: Dashboard; locale: string; t: (key:string)=>string }) { return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<UsersRound/>} label={t('admin.users')} value={String(data.metrics.totalUsers)}/><Metric icon={<Boxes/>} label={t('admin.products')} value={String(data.metrics.totalProducts)}/><Metric icon={<ShoppingCart/>} label={t('admin.orders')} value={String(data.metrics.totalOrders)}/><Metric icon={<CircleDollarSign/>} label={t('admin.revenue')} value={money(data.metrics.revenue, locale)}/></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div><AdminHeading title={t('admin.recent')}/><OrdersTable orders={data.recentOrders} locale={locale} compact t={t}/></div><div><AdminHeading title={t('admin.lowStock')}/><div className="panel mt-6 p-5">{data.lowStock.map((p) => <div key={p.id} className="flex justify-between border-b border-ink/10 py-3 last:border-0"><span><b>{p.name}</b><small className="block text-steel">{p.sku} · {p.manufacturer}</small></span><b className="text-orange">{p.stockQuantity}</b></div>)}</div></div></div></>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="panel p-6"><span className="grid size-11 place-items-center rounded-2xl bg-lime">{icon}</span><p className="mt-6 text-sm font-bold text-steel">{label}</p><b className="mt-1 block font-display text-4xl">{value}</b></div>; }
function AdminHeading({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="flex items-center justify-between"><h2 className="font-display text-3xl font-bold">{title}</h2>{action}</div>; }
function EntitySection({ title, form, children }: { title: string; form: React.ReactNode; children: React.ReactNode }) { return <section><AdminHeading title={title}/><div className="my-6">{form}</div>{children}</section>; }
function Th({ children }: { children?: React.ReactNode }) { return <th className="px-5 py-4 text-xs uppercase tracking-wider text-steel">{children}</th>; }
function Td({ children }: { children: React.ReactNode }) { return <td className="px-5 py-4 text-sm">{children}</td>; }

function OrdersTable({ orders, locale, request, reload, compact, t }: { orders: Order[]; locale: string; request?: <T>(p:string,o?:RequestInit)=>Promise<T>; reload?:()=>Promise<void>; compact?: boolean; t:(k:string)=>string }) { const next: Record<string,string[]> = {PENDING:['CONFIRMED','CANCELLED'],CONFIRMED:['PROCESSING','CANCELLED'],PROCESSING:['SHIPPED','CANCELLED'],SHIPPED:['DELIVERED'],DELIVERED:[],CANCELLED:[]}; return <div className="panel mt-6 overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-ink/10"><Th>Order</Th><Th>Customer</Th><Th>Status</Th><Th>Total</Th>{!compact && <Th/>}</tr></thead><tbody>{orders.map((o) => <tr key={o.id} className="border-b border-ink/5"><Td><b>{o.number}</b><small className="block text-steel">{new Date(o.createdAt).toLocaleDateString(locale)}</small></Td><Td>{o.user?.email ?? '—'}</Td><Td><span className="rounded-full bg-fog px-3 py-2 text-xs font-bold">{t(`status.${o.status}`)}</span></Td><Td><b>{money(o.total, locale)}</b></Td>{!compact && <Td><select aria-label="Update order status" defaultValue="" disabled={!next[o.status]?.length} onChange={async (e) => { if (!e.target.value || !request) return; await request(`/orders/${o.id}/status`, {method:'PATCH', body:JSON.stringify({status:e.target.value})}); if (reload) await reload(); }} className="rounded-xl border border-ink/10 px-2 py-2 text-xs font-bold"><option value="">Update…</option>{next[o.status]?.map((s) => <option key={s} value={s}>{t(`status.${s}`)}</option>)}</select></Td>}</tr>)}</tbody></table></div>; }

type RequestFn = <T>(path: string, options?: RequestInit) => Promise<T>;
function CategoryForm({ request, onCreated }: { request: RequestFn; onCreated:()=>void }) { const submit = async (e:FormEvent<HTMLFormElement>) => { e.preventDefault(); const v=Object.fromEntries(new FormData(e.currentTarget)); await request('/categories',{method:'POST',body:JSON.stringify({slug:v.slug,icon:v.icon,translations:[{locale:'EN',name:v.en},{locale:'UK',name:v.uk},{locale:'RU',name:v.ru}]})}); e.currentTarget.reset(); onCreated(); }; return <form onSubmit={(e)=>void submit(e)} className="panel grid gap-3 p-5 sm:grid-cols-5"><input required name="slug" placeholder="slug" className="field"/><input name="icon" placeholder="Icon" className="field"/><input required name="en" placeholder="English name" className="field"/><input required name="uk" placeholder="Українська" className="field"/><div className="flex gap-2"><input required name="ru" placeholder="Русский" className="field"/><button className="btn-primary"><Plus/></button></div></form>; }
function ManufacturerForm({ request, onCreated }: { request:RequestFn; onCreated:()=>void }) { const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));await request('/manufacturers',{method:'POST',body:JSON.stringify(v)});e.currentTarget.reset();onCreated();};return <form onSubmit={(e)=>void submit(e)} className="panel grid gap-3 p-5 sm:grid-cols-4"><input required name="name" placeholder="Name" className="field"/><input required name="slug" placeholder="slug" className="field"/><input name="country" placeholder="Country" className="field"/><button className="btn-primary"><Plus/>Add</button></form>; }
function VehicleMakeForm({ request, onCreated }: { request:RequestFn; onCreated:()=>void }) { const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));await request('/vehicles/makes',{method:'POST',body:JSON.stringify(v)});e.currentTarget.reset();onCreated();};return <form onSubmit={(e)=>void submit(e)} className="panel grid gap-3 p-5 sm:grid-cols-3"><input required name="name" placeholder="Make name" className="field"/><input required name="slug" placeholder="slug" className="field"/><button className="btn-primary"><Plus/>Add make</button></form>; }
function ProductCreateForm({ categories, manufacturers, vehicles, request, onCreated }: { categories:Category[]; manufacturers:Manufacturer[]; vehicles:VehicleMake[]; request:RequestFn; onCreated:()=>void }) { const engines=vehicles.flatMap((m)=>m.models.flatMap((model)=>model.engines.map((engine)=>({id:engine.id,label:`${m.name} ${model.name} ${engine.name}`})))); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)); const body={sku:v.sku,oemNumber:v.oemNumber,manufacturerId:v.manufacturerId,categoryId:v.categoryId,price:Number(v.price),discountPercent:Number(v.discountPercent||0),stockQuantity:Number(v.stockQuantity),images:[v.image],specifications:{warranty:'24 months',condition:'New'},translations:[{locale:'EN',name:v.en,description:v.description},{locale:'UK',name:v.uk,description:v.descriptionUk},{locale:'RU',name:v.ru,description:v.descriptionRu}],compatibility:v.engineId?[{engineId:v.engineId,fromYear:Number(v.fromYear),toYear:Number(v.toYear)}]:[]};await request('/products',{method:'POST',body:JSON.stringify(body)});onCreated();};return <form onSubmit={(e)=>void submit(e)} className="panel mt-6 grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-4"><input required name="sku" placeholder="SKU" className="field"/><input required name="oemNumber" placeholder="OEM number" className="field"/><select required name="manufacturerId" className="field"><option value="">Manufacturer</option>{manufacturers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select required name="categoryId" className="field"><option value="">Category</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required name="price" type="number" step=".01" placeholder="Price" className="field"/><input name="discountPercent" type="number" placeholder="Discount %" className="field"/><input required name="stockQuantity" type="number" placeholder="Stock" className="field"/><input required name="image" type="url" placeholder="Image URL" className="field"/><input required name="en" placeholder="English name" className="field"/><input required name="uk" placeholder="Українська назва" className="field"/><input required name="ru" placeholder="Русское название" className="field"/><select name="engineId" className="field"><option value="">No fitment</option>{engines.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><textarea required name="description" placeholder="English description" className="field lg:col-span-2"/><textarea required name="descriptionUk" placeholder="Опис українською" className="field"/><textarea required name="descriptionRu" placeholder="Описание на русском" className="field"/><input name="fromYear" type="number" defaultValue="2016" className="field"/><input name="toYear" type="number" defaultValue="2026" className="field"/><button className="btn-primary sm:col-span-2"><Plus/>Create product</button></form>; }
