'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Activity, ArrowDownLeft, ArrowUpRight, BarChart3, Bell, BookOpen, CalendarClock, ChevronRight,
  FileUp, FolderTree, Gauge, Goal, Menu, Pencil, PiggyBank,
  Plus, ReceiptText, RefreshCw, Search, Settings, ShieldCheck, Target, Trash2, TrendingDown, TrendingUp, UploadCloud,
  WalletCards, X,
} from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ApiError, api } from '@/lib/api';
import type { Locale } from '@/lib/i18n';
import { t } from '@/lib/i18n';
import type { Section } from '@/lib/sections';
import { Brand } from './brand';
import { LanguageSwitcher } from './language-switcher';

type JsonRecord = Record<string, unknown>;
type User = { id: string; email: string; firstName: string; lastName: string; primaryCurrency: string; preferredLanguage: string; theme: string; timezone: string; twoFactorEnabled: boolean };
type Account = { id: string; name: string; type: string; currency: string; initialBalance: string | number; currentBalance: string | number; description?: string };
type Category = { id: string; name: string; kind: string; color: string; isSystem?: boolean; children?: Category[] };
type Transaction = { id: string; description: string; merchant?: string; amount: string | number; currency: string; type: string; date: string; account: { id: string; name: string }; category?: { id: string; name: string; color: string } };
type Budget = { id: string; amount: string | number; currency: string; category?: Category; usage: { spent: number; limit: number; remaining: number; percentage: number; crossedThreshold: number | null; exceeded: boolean } };
type GoalItem = { id: string; name: string; targetAmount: string | number; currentAmount: string | number; currency: string; targetDate?: string; description?: string };
type Recurring = { id: string; name: string; amount: string | number; currency: string; frequency: string; nextExecution: string; enabled: boolean; account: Account; category?: Category };
type Audit = { id: string; action: string; entityType?: string; createdAt: string };
type Trend = { monthly: Array<{ month: string; income: number; expenses: number; savings: number }>; categories: Array<{ name: string; value: number; color: string }>; accountBalances: Array<{ name: string; currency: string; currentBalance: string | number }> };
type Overview = { totals: Array<{ currency: string; balance: number; income: number; expenses: number; savings: number }>; accounts: Account[]; recent: Transaction[]; upcoming: Recurring[]; goals: GoalItem[] };

const nav = [
  ['dashboard', Gauge], ['accounts', WalletCards], ['transactions', ReceiptText], ['budgets', Target], ['analytics', BarChart3],
  ['goals', Goal], ['recurring', CalendarClock], ['import', FileUp], ['categories', FolderTree], ['settings', Settings], ['security', ShieldCheck],
] as const;
const colors = ['#6758f3', '#31c992', '#f0a53b', '#ef6681', '#37a6d8', '#8b5cf6'];

function numeric(value: unknown): number { const number = Number(value ?? 0); return Number.isFinite(number) ? number : 0; }
function money(value: unknown, currency = 'UAH', locale: Locale = 'en'): string {
  const code = ['UAH', 'USD', 'EUR'].includes(currency) ? currency : 'UAH';
  const language = locale === 'ua' ? 'uk-UA' : locale === 'ru' ? 'ru-RU' : 'en-US';
  return new Intl.NumberFormat(language, { style: 'currency', currency: code, maximumFractionDigits: code === 'UAH' ? 0 : 2 }).format(numeric(value));
}
function shortDate(value: string, locale: Locale): string { return new Intl.DateTimeFormat(locale === 'ua' ? 'uk-UA' : locale, { day: '2-digit', month: 'short' }).format(new Date(value)); }
function records(value: unknown): JsonRecord[] { return Array.isArray(value) ? value.filter((item): item is JsonRecord => Boolean(item) && typeof item === 'object') : []; }

export function FinanceApp({ locale, section }: { locale: Locale; section: Section }) {
  const router = useRouter();
  const [menu, setMenu] = useState(false);
  const [user, setUser] = useState<User | null>(null);
  const [data, setData] = useState<unknown>(null);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<'unauthorized' | 'offline' | 'generic' | null>(null);
  const [dialog, setDialog] = useState<JsonRecord | 'new' | null>(null);

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const profile = await api<User>('/users/me'); setUser(profile);
      const dependencies = await Promise.all([api<Account[]>('/accounts'), api<Category[]>('/categories')]);
      setAccounts(dependencies[0]); setCategories(dependencies[1]);
      if (section === 'dashboard') {
        const [overview, trends] = await Promise.all([api<Overview>('/analytics/overview'), api<Trend>('/analytics/trends')]);
        setData({ overview, trends });
      } else if (section === 'analytics') {
        const [trends, comparison] = await Promise.all([api<Trend>('/analytics/trends'), api<JsonRecord>('/analytics/comparison')]);
        setData({ trends, comparison });
      } else if (section === 'transactions') setData(await api<{ items: Transaction[] }>('/transactions?limit=50'));
      else if (section === 'goals') setData(await api<GoalItem[]>('/goals'));
      else if (section === 'recurring') setData(await api<Recurring[]>('/recurring-payments'));
      else if (section === 'budgets') setData(await api<Budget[]>('/budgets'));
      else if (section === 'categories') {
        const rules = await api<JsonRecord[]>('/categorization-rules'); setData({ categories: dependencies[1], rules });
      } else if (section === 'security') setData(await api<Audit[]>('/audit-logs'));
      else if (section === 'import') setData(await api<JsonRecord[]>('/imports'));
      else if (section === 'accounts') setData(dependencies[0]);
      else setData(profile);
    } catch (reason) {
      setError(reason instanceof ApiError && reason.status === 401 ? 'unauthorized' : reason instanceof TypeError ? 'offline' : 'generic');
    } finally { setLoading(false); }
  }, [section]);

  useEffect(() => {
    // The async loader synchronizes this client view with the authenticated API.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  async function logout() { await api('/auth/logout', { method: 'POST' }).catch(() => undefined); router.push(`/${locale}/login`); }
  async function remove(path: string) { if (!window.confirm(t(locale, 'form.confirmDelete'))) return; await api(path, { method: 'DELETE' }); await load(); }

  const addable = ['accounts', 'transactions', 'budgets', 'goals', 'recurring', 'categories'].includes(section);
  return <div className="app-layout">
    <aside className={`sidebar ${menu ? 'open' : ''}`}>
      <div onClick={() => setMenu(false)}><Brand /></div>
      <nav className="sidebar-nav">{nav.map(([key, Icon]) => <Link onClick={() => setMenu(false)} className={section === key ? 'active' : ''} key={key} href={`/${locale}/app/${key}`}><Icon/><span>{t(locale, `nav.${key}`)}</span></Link>)}</nav>
      <div className="sidebar-bottom"><button className="profile-chip" onClick={() => router.push(`/${locale}/app/settings`)}><span className="avatar">{user ? `${user.firstName[0]}${user.lastName[0]}` : 'MT'}</span><div><strong>{user ? `${user.firstName} ${user.lastName}` : 'MoneyTrack'}</strong><small>{user?.email ?? t(locale, 'brand.tagline')}</small></div></button></div>
    </aside>
    <main className="app-main">
      <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMenu(true)} aria-label="Open menu"><Menu/></button><div className="topbar-actions"><LanguageSwitcher locale={locale}/><button className="icon-button" aria-label="Notifications"><Bell size={18}/></button><button className="button button-ghost" onClick={() => void logout()}>{t(locale, 'action.logout')}</button></div></header>
      <div className="page-content">
        <PageHeading locale={locale} section={section} user={user} addable={addable} onAdd={() => setDialog('new')}/>
        {loading ? <Loading /> : error ? <ErrorState locale={locale} type={error} retry={() => void load()}/> : <SectionContent locale={locale} section={section} data={data} accounts={accounts} categories={categories} edit={setDialog} remove={remove} reload={load}/>} 
      </div>
      <nav className="bottom-nav">{nav.slice(0,5).map(([key,Icon]) => <Link className={section===key?'active':''} key={key} href={`/${locale}/app/${key}`}><Icon size={19}/><span>{t(locale,`nav.${key}`)}</span></Link>)}</nav>
    </main>
    {dialog && <EntityDialog locale={locale} section={section} initial={dialog === 'new' ? null : dialog} accounts={accounts} categories={categories} close={() => setDialog(null)} saved={async () => { setDialog(null); await load(); }}/>} 
  </div>;
}

function PageHeading({ locale, section, user, addable, onAdd }: { locale: Locale; section: Section; user: User | null; addable: boolean; onAdd(): void }) {
  const dashboard = section === 'dashboard';
  return <div className="page-heading"><div><h1>{dashboard ? `${t(locale, 'dashboard.greeting')}, ${user?.firstName ?? 'Alex'}!` : t(locale, `page.${section}.title`)}</h1><p>{dashboard ? t(locale, 'dashboard.subtitle') : t(locale, `page.${section}.copy`)}</p></div><div className="page-heading-actions">{addable && <button className="button button-primary" onClick={onAdd}><Plus size={17}/>{t(locale,'action.add')}</button>}</div></div>;
}
function Loading() { return <div className="loading-grid" aria-label="Loading">{[1,2,3,4].map((item) => <div className="skeleton" key={item}/>)}</div>; }
function ErrorState({ locale, type, retry }: { locale: Locale; type: 'unauthorized'|'offline'|'generic'; retry(): void }) {
  return <div className="state-card"><ShieldCheck size={36}/><h2>{t(locale, type === 'unauthorized' ? 'state.unauthorized' : type === 'offline' ? 'state.offline' : 'state.error')}</h2>{type === 'unauthorized' ? <Link className="button button-primary" href={`/${locale}/login`}>{t(locale,'action.login')}</Link> : <button className="button button-primary" onClick={retry}><RefreshCw size={16}/>{t(locale,'action.retry')}</button>}</div>;
}

function SectionContent(props: { locale: Locale; section: Section; data: unknown; accounts: Account[]; categories: Category[]; edit(value: JsonRecord): void; remove(path: string): Promise<void>; reload(): Promise<void> }) {
  if (props.section === 'dashboard') return <Dashboard {...props}/>;
  if (props.section === 'accounts') return <AccountsPage {...props}/>;
  if (props.section === 'transactions') return <TransactionsPage {...props}/>;
  if (props.section === 'budgets') return <BudgetsPage {...props}/>;
  if (props.section === 'analytics') return <AnalyticsPage {...props}/>;
  if (props.section === 'goals') return <GoalsPage {...props}/>;
  if (props.section === 'recurring') return <RecurringPage {...props}/>;
  if (props.section === 'import') return <ImportPage {...props}/>;
  if (props.section === 'categories') return <CategoriesPage {...props}/>;
  if (props.section === 'settings') return <SettingsPage {...props}/>;
  return <SecurityPage {...props}/>;
}

function Dashboard({ locale, data }: { locale: Locale; data: unknown }) {
  const payload = data as { overview: Overview; trends: Trend };
  const preferred = payload.overview.totals.find((item) => item.currency === 'UAH') ?? payload.overview.totals[0] ?? { currency:'UAH', balance:0, income:0, expenses:0, savings:0 };
  const stats = [
    ['metric.balance', preferred.balance, WalletCards, '#6758f3', '#efedff'], ['metric.income', preferred.income, TrendingUp, '#159b6e', '#ddf8ed'],
    ['metric.expenses', preferred.expenses, TrendingDown, '#d64a65', '#ffebef'], ['metric.savings', preferred.savings, PiggyBank, '#d88b17', '#fff3dc'],
  ] as const;
  return <>
    <div className="stat-grid">{stats.map(([label,value,Icon,accent,tint]) => <article className="stat-card" key={label} style={{'--accent':accent,'--tint':tint} as React.CSSProperties}><div className="stat-top"><span>{t(locale,label)}</span><span className="stat-icon"><Icon size={17}/></span></div><strong>{money(value,preferred.currency,locale)}</strong><footer><b>●</b> {t(locale,'dashboard.subtitle')}</footer></article>)}</div>
    <div className="dashboard-grid"><Panel title={t(locale,'section.cashflow')}><div className="chart-wrap">{payload.trends.monthly.length ? <ResponsiveContainer><AreaChart data={payload.trends.monthly}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#6758f3" stopOpacity={.35}/><stop offset="1" stopColor="#6758f3" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#efeff5" vertical={false}/><XAxis dataKey="month" tickLine={false} axisLine={false} fontSize={10}/><YAxis hide/><Tooltip/><Area type="monotone" dataKey="income" stroke="#6758f3" fill="url(#income)" strokeWidth={2.5}/><Line type="monotone" dataKey="expenses" stroke="#ef6681" strokeWidth={2}/></AreaChart></ResponsiveContainer> : <ChartEmpty locale={locale}/>}</div></Panel>
      <Panel title={t(locale,'section.spending')}><div className="chart-wrap donut-wrap">{payload.trends.categories.length ? <ResponsiveContainer><PieChart><Pie data={payload.trends.categories} dataKey="value" nameKey="name" innerRadius="56%" outerRadius="82%" paddingAngle={3}>{payload.trends.categories.map((item,index)=><Cell key={item.name} fill={item.color || colors[index%colors.length]}/>)}</Pie><Tooltip/><Legend iconType="circle" iconSize={8}/></PieChart></ResponsiveContainer> : <ChartEmpty locale={locale}/>}</div></Panel></div>
    <div className="secondary-grid"><Panel title={t(locale,'section.recent')} action={<Link href={`/${locale}/app/transactions`} className="muted">{t(locale,'action.viewAll')} <ChevronRight size={12}/></Link>}><TransactionList locale={locale} transactions={payload.overview.recent}/></Panel><Panel title={t(locale,'section.upcoming')}><UpcomingList locale={locale} items={payload.overview.upcoming}/></Panel></div>
    <div className="secondary-grid"><Panel title={t(locale,'section.accounts')}><AccountCards locale={locale} accounts={payload.overview.accounts}/></Panel><Panel title={t(locale,'section.goals')}><GoalCards locale={locale} goals={payload.overview.goals} compact/></Panel></div>
  </>;
}
function Panel({ title, action, children }: { title:string; action?:React.ReactNode; children:React.ReactNode }) { return <section className="panel"><header className="panel-heading"><h2>{title}</h2>{action}</header>{children}</section>; }
function ChartEmpty({locale}:{locale:Locale}) { return <div className="chart-empty"><BarChart3/><span>{t(locale,'chart.noData')}</span></div>; }
function TransactionList({locale,transactions}:{locale:Locale;transactions:Transaction[]}) { return <div className="transaction-list">{transactions.length ? transactions.map((item)=><div className="transaction-row" key={item.id}><div className="transaction-main"><span className="transaction-icon">{item.type==='INCOME'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><strong>{item.merchant||item.description}</strong><small>{item.account.name}</small></div></div><span className="transaction-category">{item.category?.name??'—'}</span><time>{shortDate(item.date,locale)}</time><span className={`transaction-amount ${item.type.toLowerCase()}`}>{item.type==='INCOME'?'+':'−'} {money(item.amount,item.currency,locale)}</span></div>) : <div className="chart-empty">{t(locale,'state.empty')}</div>}</div>; }
function UpcomingList({locale,items}:{locale:Locale;items:Recurring[]}) { return <div className="upcoming-list">{items.length?items.map((item)=>{const date=new Date(item.nextExecution);return <div className="upcoming-item" key={item.id}><span className="upcoming-date"><strong>{date.getDate()}</strong>{new Intl.DateTimeFormat(locale,{month:'short'}).format(date)}</span><div><h3>{item.name}</h3><p>{t(locale,`frequency.${item.frequency}`)} · {item.account?.name}</p></div><strong>{money(item.amount,item.currency,locale)}</strong></div>}):<div className="chart-empty">{t(locale,'state.empty')}</div>}</div>; }
function AccountCards({locale,accounts,actions}:{locale:Locale;accounts:Account[];actions?:(item:Account)=>React.ReactNode}) { return <div className="account-grid">{accounts.map((account)=><article className="account-card" key={account.id}><div className="account-type"><span>{t(locale,`account.${account.type}`)}</span>{actions?.(account)}</div><h3>{account.name}</h3><strong>{money(account.currentBalance,account.currency,locale)}</strong></article>)}</div>; }
function GoalCards({locale,goals,compact=false,actions}:{locale:Locale;goals:GoalItem[];compact?:boolean;actions?:(item:GoalItem)=>React.ReactNode}) { return <div className={compact?'upcoming-list':'entity-grid'}>{goals.map((goal)=>{const percent=Math.min(100,(numeric(goal.currentAmount)/Math.max(numeric(goal.targetAmount),1))*100);return <article className={compact?'upcoming-item':'entity-card'} key={goal.id}>{compact?<><span className="goal-ring" data-value={`${Math.round(percent)}%`} style={{'--goal':`${percent*3.6}deg`} as React.CSSProperties}/><div><h3>{goal.name}</h3><p>{money(goal.currentAmount,goal.currency,locale)} / {money(goal.targetAmount,goal.currency,locale)}</p></div></>:<><div className="entity-card-head"><div><span className="pill green">{Math.round(percent)}%</span><h2 style={{marginTop:12}}>{goal.name}</h2></div>{actions?.(goal)}</div><strong className="big-number">{money(goal.currentAmount,goal.currency,locale)}</strong><p>{t(locale,'goal.target')}: {money(goal.targetAmount,goal.currency,locale)}</p><div className="progress"><span style={{width:`${percent}%`}}/></div><div className="progress-meta"><span>{t(locale,'goal.saved')}</span><span>{Math.round(percent)}%</span></div></>}</article>})}</div>; }

function AccountsPage({locale,data,edit,remove}:{locale:Locale;data:unknown;edit(v:JsonRecord):void;remove(p:string):Promise<void>}) { const items=data as Account[]; return items.length?<div className="entity-grid"><AccountCards locale={locale} accounts={items} actions={(item)=><CardActions edit={()=>edit(item as unknown as JsonRecord)} remove={()=>void remove(`/accounts/${item.id}`)}/>} /></div>:<Empty locale={locale}/>; }
function TransactionsPage({locale,data,edit,remove}:{locale:Locale;data:unknown;edit(v:JsonRecord):void;remove(p:string):Promise<void>}) { const items=(data as {items:Transaction[]}).items; return <><div className="filter-bar"><div className="filter-search"><Search size={17}/><input placeholder={t(locale,'filter.search')}/></div><select aria-label={t(locale,'filter.period')}><option>{t(locale,'filter.period')}</option><option>7 days</option><option>Month</option><option>Year</option></select></div><div className="data-table"><div className="table-header"><span>{t(locale,'table.description')}</span><span>{t(locale,'table.account')}</span><span>{t(locale,'table.category')}</span><span>{t(locale,'table.date')}</span><span>{t(locale,'table.amount')}</span></div>{items.map((item)=><div className="table-record" key={item.id}><div className="transaction-main"><span className="transaction-icon">{item.type==='INCOME'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><strong>{item.merchant||item.description}</strong><small>{item.description}</small></div></div><span>{item.account.name}</span><span>{item.category?.name??'—'}</span><time>{shortDate(item.date,locale)}</time><span className={`transaction-amount ${item.type.toLowerCase()}`}>{item.type==='INCOME'?'+':'−'} {money(item.amount,item.currency,locale)} <button className="mini-button" onClick={()=>edit(item as unknown as JsonRecord)}><Pencil size={13}/></button>{item.type!=='TRANSFER'&&<button className="mini-button" onClick={()=>void remove(`/transactions/${item.id}`)}><Trash2 size={13}/></button>}</span></div>)}</div></>; }
function BudgetsPage({locale,data,edit,remove}:{locale:Locale;data:unknown;edit(v:JsonRecord):void;remove(p:string):Promise<void>}) { const items=data as Budget[]; return items.length?<div className="entity-grid">{items.map((item)=>{const usage=item.usage;return <article className={`entity-card budget-card ${usage.exceeded?'danger':usage.percentage>=90?'warning':''}`} key={item.id}><div className="entity-card-head"><div><span className={`pill ${usage.exceeded?'rose':''}`}>{usage.exceeded?t(locale,'budget.exceeded'):`${Math.round(usage.percentage)}% ${t(locale,'budget.used')}`}</span><h2 style={{marginTop:12}}>{item.category?.name??t(locale,'generic.totalBudget')}</h2></div><CardActions edit={()=>edit(item as unknown as JsonRecord)} remove={()=>void remove(`/budgets/${item.id}`)}/></div><strong className="big-number">{money(usage.spent,item.currency,locale)} <small className="muted">/ {money(usage.limit,item.currency,locale)}</small></strong><div className="progress" style={{'--progress':usage.exceeded?'#ef6681':usage.percentage>=90?'#f0a53b':'#6758f3'} as React.CSSProperties}><span style={{width:`${Math.min(100,usage.percentage)}%`}}/></div><div className="progress-meta"><span>{t(locale,'budget.remaining')}</span><span>{money(usage.remaining,item.currency,locale)}</span></div></article>})}</div>:<Empty locale={locale}/>; }
function AnalyticsPage({locale,data}:{locale:Locale;data:unknown}) { const payload=data as {trends:Trend;comparison:JsonRecord}; const comparison=payload.comparison.expenses as JsonRecord|undefined; return <><div className="stat-grid"><article className="stat-card"><div className="stat-top">{t(locale,'section.monthComparison')}<TrendingDown size={18}/></div><strong>{money(comparison?.current,'UAH',locale)}</strong><footer>{numeric(comparison?.difference)<=0?'↓':'↑'} {comparison?.percentage===null?'—':`${Math.abs(numeric(comparison?.percentage)).toFixed(1)}%`}</footer></article>{payload.trends.accountBalances.slice(0,3).map((item)=><article className="stat-card" key={item.name}><div className="stat-top">{item.name}<WalletCards size={18}/></div><strong>{money(item.currentBalance,item.currency,locale)}</strong><footer>{t(locale,'metric.balance')}</footer></article>)}</div><div className="dashboard-grid"><Panel title={`${t(locale,'chart.income')} vs ${t(locale,'chart.expenses')}`}><div className="chart-wrap"><ResponsiveContainer><BarChart data={payload.trends.monthly}><CartesianGrid vertical={false} stroke="#efeff5"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip/><Legend/><Bar dataKey="income" fill="#6758f3" radius={[5,5,0,0]}/><Bar dataKey="expenses" fill="#ef6681" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title={t(locale,'section.spending')}><div className="chart-wrap"><ResponsiveContainer><PieChart><Pie data={payload.trends.categories} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="80%">{payload.trends.categories.map((item,index)=><Cell key={item.name} fill={item.color||colors[index%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></Panel></div><div className="panel" style={{marginTop:16}}><div className="panel-heading"><h2>{t(locale,'chart.savings')}</h2></div><div className="chart-wrap"><ResponsiveContainer><LineChart data={payload.trends.monthly}><CartesianGrid vertical={false} stroke="#efeff5"/><XAxis dataKey="month" axisLine={false}/><YAxis hide/><Tooltip/><Line type="monotone" dataKey="savings" stroke="#31c992" strokeWidth={3}/></LineChart></ResponsiveContainer></div></div></>; }
function GoalsPage({locale,data,edit,remove}:{locale:Locale;data:unknown;edit(v:JsonRecord):void;remove(p:string):Promise<void>}) { const goals=data as GoalItem[]; return goals.length?<GoalCards locale={locale} goals={goals} actions={(item)=><CardActions edit={()=>edit(item as unknown as JsonRecord)} remove={()=>void remove(`/goals/${item.id}`)}/>}/>:<Empty locale={locale}/>; }
function RecurringPage({locale,data,edit,remove}:{locale:Locale;data:unknown;edit(v:JsonRecord):void;remove(p:string):Promise<void>}) { const items=data as Recurring[]; return items.length?<div className="entity-grid">{items.map((item)=><article className="entity-card" key={item.id}><div className="entity-card-head"><span className={`pill ${item.enabled?'green':'rose'}`}>{t(locale,`frequency.${item.frequency}`)}</span><CardActions edit={()=>edit(item as unknown as JsonRecord)} remove={()=>void remove(`/recurring-payments/${item.id}`)}/></div><h2 style={{marginTop:16}}>{item.name}</h2><strong className="big-number">{money(item.amount,item.currency,locale)}</strong><p>{t(locale,'recurring.next')}: {shortDate(item.nextExecution,locale)} · {item.account.name}</p></article>)}</div>:<Empty locale={locale}/>; }

function ImportPage({locale,accounts,reload,data}:{locale:Locale;accounts:Account[];reload():Promise<void>;data:unknown}) {
  const [accountId,setAccountId]=useState(accounts[0]?.id??''); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<JsonRecord|null>(null); const [busy,setBusy]=useState(false); const jobs=records(data);
  async function upload(){if(!file||!accountId)return;setBusy(true);const body=new FormData();body.set('file',file);body.set('accountId',accountId);try{setPreview(await api<JsonRecord>('/imports/preview',{method:'POST',body}));}finally{setBusy(false)}}
  async function confirm(){if(!preview?.id)return;setBusy(true);try{await api(`/imports/${String(preview.id)}/confirm`,{method:'POST',body:JSON.stringify({mapping:preview.mapping})});setPreview(null);setFile(null);await reload();}finally{setBusy(false)}}
  return <><section className="dropzone"><span className="dropzone-icon"><UploadCloud/></span><h2>{t(locale,'import.drop')}</h2><p>{t(locale,'import.help')}</p><div className="form-grid"><select value={accountId} onChange={(e)=>setAccountId(e.target.value)}>{accounts.map((account)=><option value={account.id} key={account.id}>{account.name}</option>)}</select><input type="file" accept=".csv,.xlsx" onChange={(e)=>setFile(e.target.files?.[0]??null)}/></div><button className="button button-primary" disabled={!file||busy} onClick={()=>void upload()}>{busy?t(locale,'state.loading'):t(locale,'action.upload')}</button></section><div className="import-steps">{['1','2','3','4'].map((number)=><div key={number}><span>{number}</span><strong>{t(locale,`import.step${number}`)}</strong></div>)}</div>{preview&&<section className="panel" style={{marginTop:16}}><div className="panel-heading"><h2>{t(locale,'import.preview')}</h2><button className="button button-primary" onClick={()=>void confirm()}>{t(locale,'action.confirmImport')}</button></div><p>{String(preview.totalRows)} {t(locale,'generic.rows')} · {records(preview.preview).filter((row)=>Array.isArray(row.errors)&&row.errors.length===0).length} {t(locale,'generic.previewed')}</p></section>}{jobs.length>0&&<section className="panel" style={{marginTop:16}}><div className="panel-heading"><h2>{t(locale,'import.history')}</h2></div>{jobs.map((job)=><div className="toggle-row" key={String(job.id)}><div><h3>{String(job.fileName)}</h3><p>{String(job.status)} · {String(job.importedCount??0)} {t(locale,'generic.imported')} · {String(job.skippedCount??0)} {t(locale,'generic.skipped')}</p></div></div>)}</section>}</>;
}
function CategoriesPage({locale,data,edit,remove}:{locale:Locale;data:unknown;edit(v:JsonRecord):void;remove(p:string):Promise<void>}) { const payload=data as {categories:Category[];rules:JsonRecord[]}; return <div className="settings-grid"><section className="settings-section"><h2>{t(locale,'categories.title')}</h2><p>{t(locale,'categories.copy')}</p><div className="upcoming-list">{payload.categories.map((item)=><div className="upcoming-item" key={item.id}><span className="transaction-icon" style={{color:item.color}}><FolderTree/></span><div><h3>{item.name}</h3><p>{item.kind} · {item.children?.length??0} {t(locale,'categories.subcategories')}</p></div><button className="mini-button" onClick={()=>edit(item as unknown as JsonRecord)}><Pencil size={13}/></button>{!item.isSystem&&<button className="mini-button" onClick={()=>void remove(`/categories/${item.id}`)}><Trash2 size={13}/></button>}</div>)}</div></section><section className="settings-section"><h2>{t(locale,'categories.rules')}</h2><p>{t(locale,'categories.rulesCopy')}</p><div className="upcoming-list">{payload.rules.map((rule)=><div className="upcoming-item" key={String(rule.id)}><span className="transaction-icon"><RefreshCw/></span><div><h3>{String(rule.matchField)} {String(rule.operator).toLowerCase()} “{String(rule.matchValue)}”</h3><p>→ {String((rule.category as JsonRecord)?.name??t(locale,'field.category'))} · {t(locale,'categories.priority')} {String(rule.priority)}</p></div></div>)}</div></section></div>; }
function SettingsPage({locale,data,reload}:{locale:Locale;data:unknown;reload():Promise<void>}) { const profile=data as User; async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));await api('/users/me',{method:'PATCH',body:JSON.stringify(values)});await reload()} const alerts=['settings.budgetAlerts','settings.recurringAlerts','settings.importAlerts']; return <div className="settings-grid"><section className="settings-section"><h2>{t(locale,'settings.profile')}</h2><p>{t(locale,'page.settings.copy')}</p><form className="finance-form" onSubmit={(event)=>void submit(event)}><div className="form-grid"><label>{t(locale,'field.firstName')}<input name="firstName" defaultValue={profile.firstName}/></label><label>{t(locale,'field.lastName')}<input name="lastName" defaultValue={profile.lastName}/></label></div><div className="form-grid"><label>{t(locale,'settings.primaryCurrency')}<select name="primaryCurrency" defaultValue={profile.primaryCurrency}><option>UAH</option><option>USD</option><option>EUR</option></select></label><label>{t(locale,'settings.language')}<select name="preferredLanguage" defaultValue={profile.preferredLanguage}><option>EN</option><option>UA</option><option>RU</option></select></label></div><div className="form-grid"><label>{t(locale,'settings.theme')}<select name="theme" defaultValue={profile.theme}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>{t(locale,'settings.timezone')}<input name="timezone" defaultValue={profile.timezone}/></label></div><button className="button button-primary">{t(locale,'action.save')}</button></form></section><section className="settings-section"><h2>{t(locale,'settings.notifications')}</h2><p>{t(locale,'settings.notificationsCopy')}</p>{alerts.map((key)=><div className="toggle-row" key={key}><div><h3>{t(locale,key)}</h3><p>{t(locale,'settings.notificationHelp')}</p></div><button className="switch on" aria-label={t(locale,key)}/></div>)}</section></div>; }
function SecurityPage({locale,data}:{locale:Locale;data:unknown}) { const logs=data as Audit[]; return <div className="settings-grid"><section className="settings-section"><h2>{t(locale,'page.security.title')}</h2><p>{t(locale,'page.security.copy')}</p><div className="toggle-row"><div><h3>{t(locale,'security.password')}</h3><p>{t(locale,'security.passwordCopy')}</p></div><button className="button button-ghost">{t(locale,'action.update')}</button></div><div className="toggle-row"><div><h3>{t(locale,'security.twoFactor')}</h3><p>{t(locale,'security.twoFactorCopy')}</p></div><button className="button button-ghost">{t(locale,'security.enable')}</button></div><div className="toggle-row"><div><h3>{t(locale,'security.sessions')}</h3><p>{t(locale,'security.sessionsCopy')}</p></div><span className="pill green">{t(locale,'security.protected')}</span></div></section><section className="settings-section"><h2>{t(locale,'security.audit')}</h2><p>{t(locale,'security.auditCopy')}</p><div className="upcoming-list">{logs.map((log)=><div className="upcoming-item" key={log.id}><span className="transaction-icon"><Activity/></span><div><h3>{log.action.replaceAll('_',' ')}</h3><p>{log.entityType??t(locale,'field.account')} · {shortDate(log.createdAt,locale)}</p></div></div>)}</div></section></div>; }
function Empty({locale}:{locale:Locale}) { return <div className="state-card"><BookOpen/><h2>{t(locale,'state.empty')}</h2><p>{t(locale,'dashboard.subtitle')}</p></div>; }
function CardActions({edit,remove}:{edit():void;remove():void}) { return <span className="card-actions"><button className="mini-button" onClick={edit}><Pencil size={13}/></button><button className="mini-button" onClick={remove}><Trash2 size={13}/></button></span>; }

function EntityDialog({locale,section,initial,accounts,categories,close,saved}:{locale:Locale;section:Section;initial:JsonRecord|null;accounts:Account[];categories:Category[];close():void;saved():Promise<void>}) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const config=useMemo(()=>entityConfig(section,locale,accounts,categories),[section,locale,accounts,categories]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=Object.fromEntries(new FormData(event.currentTarget));const payload:JsonRecord={...form};for(const [key,value] of Object.entries(payload))if(value==='')delete payload[key];for(const key of ['amount','initialBalance','currentAmount','targetAmount'])if(payload[key]!==undefined)payload[key]=Number(payload[key]);if(section==='budgets')payload.alertThresholds=[80,90,100];try{await api(initial?`${config.endpoint}/${String(initial.id)}`:config.endpoint,{method:initial?'PATCH':'POST',body:JSON.stringify(payload)});await saved()}catch(reason){setError(reason instanceof Error?reason.message:t(locale,'state.error'));setBusy(false)}}
  const fields=initial&&section==='accounts'?config.fields.filter((field)=>!['currency','initialBalance'].includes(field.name)):config.fields;
  return <div className="drawer-backdrop" role="presentation" onMouseDown={(event)=>{if(event.currentTarget===event.target)close()}}><section className="dialog" role="dialog" aria-modal="true"><header className="dialog-header"><h2>{initial?t(locale,'action.edit'):t(locale,'action.add')} {t(locale,`nav.${section}`)}</h2><button className="mini-button" onClick={close}><X/></button></header><form className="finance-form" onSubmit={(event)=>void submit(event)}>{fields.map((field)=><label key={field.name}>{field.label}{field.type==='select'?<select name={field.name} defaultValue={String(initial?.[field.name]??field.defaultValue??'')} required={field.required}>{field.options?.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>:<input name={field.name} type={field.type} step={field.step} required={field.required} defaultValue={String(initial?.[field.name]??field.defaultValue??'')}/>}</label>)}{error&&<div className="form-error">{error}</div>}<footer className="dialog-footer"><button type="button" className="button button-ghost" onClick={close}>{t(locale,'action.cancel')}</button><button className="button button-primary" disabled={busy}>{busy?t(locale,'state.loading'):t(locale,'action.save')}</button></footer></form></section></div>;
}
type Field = {name:string;label:string;type:string;required?:boolean;step?:string;defaultValue?:string;options?:Array<[string,string]>};
function entityConfig(section:Section,locale:Locale,accounts:Account[],categories:Category[]):{endpoint:string;fields:Field[]} {
  const accountOptions=accounts.map((item):[string,string]=>[item.id,item.name]);const categoryOptions=categories.filter((item)=>item.kind==='EXPENSE').map((item):[string,string]=>[item.id,item.name]);
  const currency:Array<[string,string]>=[['UAH','UAH'],['USD','USD'],['EUR','EUR']]; const today=new Date().toISOString().slice(0,10);
  if(section==='accounts')return{endpoint:'/accounts',fields:[{name:'name',label:t(locale,'field.name'),type:'text',required:true},{name:'type',label:t(locale,'field.type'),type:'select',required:true,options:[['BANK',t(locale,'account.BANK')],['CASH',t(locale,'account.CASH')],['SAVINGS',t(locale,'account.SAVINGS')],['OTHER',t(locale,'account.OTHER')]]},{name:'currency',label:t(locale,'field.currency'),type:'select',required:true,options:currency},{name:'initialBalance',label:t(locale,'field.initialBalance'),type:'number',step:'0.01',required:true,defaultValue:'0'},{name:'description',label:t(locale,'field.description'),type:'text'}]};
  if(section==='transactions')return{endpoint:'/transactions',fields:[{name:'description',label:t(locale,'field.description'),type:'text',required:true},{name:'merchant',label:t(locale,'field.merchant'),type:'text'},{name:'accountId',label:t(locale,'field.account'),type:'select',required:true,options:accountOptions},{name:'categoryId',label:t(locale,'field.category'),type:'select',options:[['',t(locale,'generic.automatic')],...categoryOptions]},{name:'type',label:t(locale,'field.type'),type:'select',required:true,options:[['EXPENSE',t(locale,'transaction.EXPENSE')],['INCOME',t(locale,'transaction.INCOME')]]},{name:'amount',label:t(locale,'field.amount'),type:'number',step:'0.01',required:true},{name:'currency',label:t(locale,'field.currency'),type:'select',required:true,options:currency},{name:'date',label:t(locale,'field.date'),type:'date',required:true,defaultValue:today}]};
  if(section==='budgets')return{endpoint:'/budgets',fields:[{name:'categoryId',label:t(locale,'field.category'),type:'select',options:[['',t(locale,'generic.totalBudget')],...categoryOptions]},{name:'amount',label:t(locale,'field.amount'),type:'number',step:'0.01',required:true},{name:'currency',label:t(locale,'field.currency'),type:'select',required:true,options:currency},{name:'month',label:t(locale,'field.month'),type:'date',required:true,defaultValue:today.slice(0,8)+'01'}]};
  if(section==='goals')return{endpoint:'/goals',fields:[{name:'name',label:t(locale,'field.name'),type:'text',required:true},{name:'targetAmount',label:t(locale,'goal.target'),type:'number',step:'0.01',required:true},{name:'currentAmount',label:t(locale,'goal.saved'),type:'number',step:'0.01',defaultValue:'0'},{name:'currency',label:t(locale,'field.currency'),type:'select',required:true,options:currency},{name:'targetDate',label:t(locale,'field.date'),type:'date'},{name:'description',label:t(locale,'field.description'),type:'text'}]};
  if(section==='recurring')return{endpoint:'/recurring-payments',fields:[{name:'name',label:t(locale,'field.name'),type:'text',required:true},{name:'accountId',label:t(locale,'field.account'),type:'select',required:true,options:accountOptions},{name:'categoryId',label:t(locale,'field.category'),type:'select',options:categoryOptions},{name:'amount',label:t(locale,'field.amount'),type:'number',step:'0.01',required:true},{name:'currency',label:t(locale,'field.currency'),type:'select',required:true,options:currency},{name:'type',label:t(locale,'field.type'),type:'select',options:[['EXPENSE',t(locale,'transaction.EXPENSE')],['INCOME',t(locale,'transaction.INCOME')]]},{name:'frequency',label:t(locale,'field.frequency'),type:'select',options:[['WEEKLY',t(locale,'frequency.WEEKLY')],['MONTHLY',t(locale,'frequency.MONTHLY')],['YEARLY',t(locale,'frequency.YEARLY')]]},{name:'nextExecution',label:t(locale,'recurring.next'),type:'date',required:true,defaultValue:today}]};
  return{endpoint:'/categories',fields:[{name:'name',label:t(locale,'field.name'),type:'text',required:true},{name:'kind',label:t(locale,'field.type'),type:'select',required:true,options:[['EXPENSE',t(locale,'transaction.EXPENSE')],['INCOME',t(locale,'transaction.INCOME')]]},{name:'color',label:t(locale,'field.color'),type:'color',defaultValue:'#6758f3'}]};
}
