'use client';

import { ArrowRight, CalendarDays, CarFront, CheckCircle2, Clock3, Gauge, MapPin, ShieldCheck, Sparkles, Wrench } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiRequest } from '@/lib/api';
import { dictionary } from '@/lib/i18n';
import { Location, WorkshopService } from '@/lib/types';

const icons = [Wrench, Gauge, ShieldCheck, Sparkles, CarFront, Clock3];

export function HomeContent({ locale }: { locale: string }) {
  const d = dictionary(locale);
  const [services, setServices] = useState<WorkshopService[]>([]);
  const [locations, setLocations] = useState<Location[]>([]);
  useEffect(() => { void Promise.all([apiRequest<WorkshopService[]>(`/services?locale=${locale}`), apiRequest<Location[]>('/locations')]).then(([s, l]) => { setServices(s); setLocations(l); }); }, [locale]);
  return <>
    <section className="hero"><div className="shell hero-grid">
      <div className="hero-copy"><span className="eyebrow">{d.hero.eyebrow}</span><h1 className="display">{d.hero.title.split(' ').slice(0, -1).join(' ')} <em>{d.hero.title.split(' ').at(-1)}</em></h1><p>{d.hero.body}</p><div className="hero-actions"><Link className="button button-primary" href={`/${locale}/book`}>{d.hero.cta}<ArrowRight size={18} /></Link><a className="button button-ghost" href="#services">{d.hero.secondary}</a></div><div className="trust-line"><span>★★★★★</span>{d.hero.trust}</div></div>
      <div className="hero-visual" aria-label="Live workshop scheduling visualization"><div className="service-orbit" /><div className="garage-card"><div className="garage-card-top"><div><span className="live-dot">Live capacity</span><h3>Central Workshop</h3><small>3 technicians · 2 bays available</small></div><CalendarDays size={30} color="#c7f44b" /></div><div className="timeline"><span /><span /><span /><span /></div></div></div>
    </div></section>
    <section className="metrics"><div className="shell metrics-grid"><div className="metric"><strong>12</strong><span>certified services</span></div><div className="metric"><strong>5</strong><span>specialist mechanics</span></div><div className="metric"><strong>30 min</strong><span>booking increments</span></div><div className="metric"><strong>0</strong><span>double bookings</span></div></div></section>
    <section className="section" id="services"><div className="shell"><div className="section-head"><div><span className="eyebrow">Workshop menu</span><h2 className="display">{d.home.servicesTitle}</h2></div><p>{d.home.servicesBody}</p></div><div className="services-grid">{services.slice(0, 6).map((service, index) => { const Icon = icons[index % icons.length]; return <Link href={`/${locale}/book?service=${service.id}`} className="service-card" key={service.id}><span className="icon-box"><Icon size={22} /></span><h3>{service.name}</h3><p>{service.description}</p><div className="service-meta"><span>€{service.price}</span><span>{service.durationMinutes} min →</span></div></Link>; })}</div></div></section>
    <section className="section dark-section" id="process"><div className="shell"><div className="section-head"><div><span className="eyebrow">Three clear steps</span><h2 className="display">{d.home.howTitle}</h2></div></div><div className="process-grid"><div className="process-card"><strong>01</strong><h3>Tell us what you drive</h3><p>Save one or more vehicles. Service recommendations and every booking stay linked to the right car.</p></div><div className="process-card"><strong>02</strong><h3>Choose live availability</h3><p>The engine checks business hours, closures, technicians, bays and current reservations in real time.</p></div><div className="process-card"><strong>03</strong><h3>Arrive with confidence</h3><p>Receive status updates, manage your visit and keep a complete service history in one account.</p></div></div><div className="advantage-banner"><CheckCircle2 size={30} />{d.home.advantage}</div></div></section>
    <section className="section" id="locations"><div className="shell"><div className="section-head"><div><span className="eyebrow">Kyiv network</span><h2 className="display">{d.home.locationsTitle}</h2></div></div><div className="locations-grid">{locations.map((location) => <article className="location-card" key={location.id}><div className="map-pattern"><span className="map-pin"><MapPin /></span></div><div className="location-body"><h3>{location.name}</h3><p>{location.address}</p><div className="location-stats"><span>{location._count.mechanics} mechanics</span><span>{location.serviceBays.length} service bays</span><span>Mon–Sat</span></div></div></article>)}</div></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">Driver stories</span><h2 className="display">{d.home.reviewsTitle}</h2></div></div><div className="reviews-grid"><article className="review-card featured"><div className="stars">★★★★★</div><blockquote>“I could see real availability, booked my brakes in two minutes, and followed every status change from my phone.”</blockquote><div className="reviewer"><span className="avatar">MK</span><span>Maria K. · Volkswagen Golf</span></div></article><article className="review-card"><div className="stars">★★★★★</div><blockquote>“Clear pricing and no waiting around when I arrived.”</blockquote><div className="reviewer"><span className="avatar">OS</span><span>Oleh S. · Ford Focus</span></div></article><article className="review-card"><div className="stars">★★★★★</div><blockquote>“Rescheduling was easier than making a phone call.”</blockquote><div className="reviewer"><span className="avatar">AN</span><span>Anna N. · Toyota Corolla</span></div></article></div></div></section>
    <section className="section"><div className="shell faq-grid"><div><span className="eyebrow">Need to know</span><h2 className="display">{d.home.faqTitle}</h2><p>Transparent service begins before you arrive.</p></div><div className="faq-list"><details open><summary>Is the selected time guaranteed?</summary><p>Yes. The API validates the slot inside a database transaction and assigns both a technician and service bay.</p></details><details><summary>Can I move or cancel a visit?</summary><p>Upcoming pending and confirmed bookings can be rescheduled or cancelled from My Garage.</p></details><details><summary>Do you take payment online?</summary><p>This portfolio demo shows price estimates only and never asks for card details.</p></details></div></div></section>
  </>;
}
