export const locales = ['en', 'uk', 'ru'] as const;
export type Locale = (typeof locales)[number];

type Dictionary = Record<string, string | Record<string, string>>;

const en: Dictionary = {
  nav: { catalog: 'Catalog', garage: 'My garage', orders: 'Orders', admin: 'Admin', login: 'Sign in', cart: 'Cart' },
  common: { viewAll: 'View all', addToCart: 'Add to cart', inStock: 'In stock', outOfStock: 'Out of stock', loading: 'Loading…', retry: 'Try again', save: 'Save', cancel: 'Cancel', search: 'Search by part, SKU or OEM', from: 'From' },
  hero: { eyebrow: 'Right part. First time.', title: 'Built for the road ahead.', text: 'OE-quality parts, precise vehicle matching and transparent pricing — all in one focused workshop.', shop: 'Shop all parts', fitment: 'Find parts for my car', stat1: 'parts ready to ship', stat2: 'fitment checked', stat3: 'day returns' },
  home: { categories: 'Shop by system', categoriesText: 'Everything your car needs, organized the way a workshop thinks.', popular: 'Workshop favourites', newest: 'Fresh on the shelf', deals: 'Limited-run deals', benefits: 'Why drivers choose us', precision: 'Precision fitment', precisionText: 'Compatibility verified against make, model, year and engine.', fast: 'Fast dispatch', fastText: 'In-stock orders leave our warehouse within one business day.', support: 'Human expertise', supportText: 'Real parts specialists, not a script, when the fit is complicated.' },
  vehicle: { eyebrow: 'Fitment finder', title: 'What do you drive?', make: 'Make', model: 'Model', year: 'Year', engine: 'Engine', choose: 'Choose…', button: 'Show compatible parts' },
  catalog: { title: 'Parts catalog', text: 'Filter a focused inventory of workshop-grade components.', filters: 'Filters', category: 'Category', manufacturer: 'Manufacturer', price: 'Price range', available: 'In stock only', discount: 'On sale', sort: 'Sort', popularity: 'Most popular', newest: 'Newest', priceAsc: 'Price: low to high', priceDesc: 'Price: high to low', results: 'results', noResults: 'No parts matched these filters.' },
  product: { sku: 'SKU', oem: 'OEM number', fitment: 'Compatible vehicles', specifications: 'Specifications', quantity: 'Quantity', related: 'Related parts', warranty: '24-month warranty', shipping: 'Dispatches in 1 business day' },
  auth: { loginTitle: 'Welcome back', registerTitle: 'Create your account', email: 'Email', password: 'Password', firstName: 'First name', lastName: 'Last name', signIn: 'Sign in', register: 'Create account', noAccount: 'New here?', haveAccount: 'Already registered?', logout: 'Sign out', error: 'Please check your details and try again.' },
  cart: { title: 'Your cart', empty: 'Your cart is waiting for the right parts.', subtotal: 'Subtotal', discount: 'Discount', shipping: 'Shipping', total: 'Total', checkout: 'Secure checkout', remove: 'Remove', stockError: 'Quantity exceeds current stock.' },
  checkout: { title: 'Checkout', contact: 'Contact information', shipping: 'Shipping information', payment: 'Payment method', summary: 'Order summary', demo: 'DEMO PAYMENT', demoText: 'No real card data is collected. Approval is simulated safely.', card: 'Demo card', cod: 'Cash on delivery', place: 'Place demo order', success: 'Order confirmed', line1: 'Street address', line2: 'Apartment / unit', city: 'City', region: 'Region', postal: 'Postal code', country: 'Country code', phone: 'Phone' },
  account: { title: 'My account', profile: 'Profile', orders: 'Order history', noOrders: 'You have not placed an order yet.' },
  admin: { title: 'Operations dashboard', users: 'Users', products: 'Products', orders: 'Orders', revenue: 'Revenue', recent: 'Recent orders', lowStock: 'Low stock', categories: 'Categories', manufacturers: 'Manufacturers', vehicles: 'Vehicles', audit: 'Audit log', access: 'Administrator access required' },
  status: { PENDING: 'Pending', CONFIRMED: 'Confirmed', PROCESSING: 'Processing', SHIPPED: 'Shipped', DELIVERED: 'Delivered', CANCELLED: 'Cancelled' },
  footer: { text: 'Parts that fit. Support that stays.', shop: 'Shop', company: 'Company', help: 'Help', rights: 'AutoParts Store. Portfolio demonstration project.' },
};

const uk: Dictionary = {
  nav: { catalog: 'Каталог', garage: 'Мій гараж', orders: 'Замовлення', admin: 'Адмін', login: 'Увійти', cart: 'Кошик' },
  common: { viewAll: 'Переглянути все', addToCart: 'До кошика', inStock: 'В наявності', outOfStock: 'Немає в наявності', loading: 'Завантаження…', retry: 'Спробувати ще', save: 'Зберегти', cancel: 'Скасувати', search: 'Пошук за назвою, SKU або OEM', from: 'Від' },
  hero: { eyebrow: 'Правильна деталь. З першого разу.', title: 'Створено для дороги попереду.', text: 'Запчастини OE-якості, точний підбір за авто та прозорі ціни — в одному магазині.', shop: 'Усі запчастини', fitment: 'Підібрати для авто', stat1: 'деталей готові до відправки', stat2: 'сумісність перевірено', stat3: 'днів на повернення' },
  home: { categories: 'За системою авто', categoriesText: 'Все потрібне для авто — організовано так, як мислить майстерня.', popular: 'Вибір майстрів', newest: 'Нові надходження', deals: 'Спеціальні пропозиції', benefits: 'Чому обирають нас', precision: 'Точна сумісність', precisionText: 'Перевіряємо марку, модель, рік і двигун.', fast: 'Швидке відправлення', fastText: 'Товар у наявності відправляємо за один робочий день.', support: 'Людська експертиза', supportText: 'Допомагають фахівці із запчастин, а не скрипт.' },
  vehicle: { eyebrow: 'Підбір за авто', title: 'Яке у вас авто?', make: 'Марка', model: 'Модель', year: 'Рік', engine: 'Двигун', choose: 'Оберіть…', button: 'Показати сумісні деталі' },
  catalog: { title: 'Каталог запчастин', text: 'Фільтруйте добірний асортимент компонентів професійного рівня.', filters: 'Фільтри', category: 'Категорія', manufacturer: 'Виробник', price: 'Діапазон цін', available: 'Тільки в наявності', discount: 'Зі знижкою', sort: 'Сортування', popularity: 'Популярні', newest: 'Нові', priceAsc: 'Ціна: за зростанням', priceDesc: 'Ціна: за спаданням', results: 'результатів', noResults: 'За цими фільтрами нічого не знайдено.' },
  product: { sku: 'SKU', oem: 'OEM номер', fitment: 'Сумісні автомобілі', specifications: 'Характеристики', quantity: 'Кількість', related: 'Схожі товари', warranty: 'Гарантія 24 місяці', shipping: 'Відправка за 1 робочий день' },
  auth: { loginTitle: 'З поверненням', registerTitle: 'Створіть обліковий запис', email: 'Email', password: 'Пароль', firstName: "Ім'я", lastName: 'Прізвище', signIn: 'Увійти', register: 'Зареєструватися', noAccount: 'Вперше тут?', haveAccount: 'Вже зареєстровані?', logout: 'Вийти', error: 'Перевірте дані та повторіть спробу.' },
  cart: { title: 'Ваш кошик', empty: 'Кошик чекає на потрібні деталі.', subtotal: 'Сума', discount: 'Знижка', shipping: 'Доставка', total: 'Разом', checkout: 'Перейти до оформлення', remove: 'Видалити', stockError: 'Кількість перевищує наявний запас.' },
  checkout: { title: 'Оформлення', contact: 'Контактні дані', shipping: 'Адреса доставки', payment: 'Спосіб оплати', summary: 'Ваше замовлення', demo: 'ДЕМО-ОПЛАТА', demoText: 'Ми не збираємо дані картки. Схвалення безпечно імітується.', card: 'Демо-картка', cod: 'Оплата при отриманні', place: 'Створити демо-замовлення', success: 'Замовлення підтверджено', line1: 'Адреса', line2: 'Квартира / офіс', city: 'Місто', region: 'Область', postal: 'Поштовий індекс', country: 'Код країни', phone: 'Телефон' },
  account: { title: 'Мій кабінет', profile: 'Профіль', orders: 'Історія замовлень', noOrders: 'Ви ще не створювали замовлень.' },
  admin: { title: 'Панель керування', users: 'Користувачі', products: 'Товари', orders: 'Замовлення', revenue: 'Дохід', recent: 'Останні замовлення', lowStock: 'Малий запас', categories: 'Категорії', manufacturers: 'Виробники', vehicles: 'Автомобілі', audit: 'Журнал аудиту', access: 'Потрібні права адміністратора' },
  status: { PENDING: 'Очікує', CONFIRMED: 'Підтверджено', PROCESSING: 'Обробляється', SHIPPED: 'Відправлено', DELIVERED: 'Доставлено', CANCELLED: 'Скасовано' },
  footer: { text: 'Деталі, що підходять. Підтримка, що залишається.', shop: 'Магазин', company: 'Компанія', help: 'Допомога', rights: 'AutoParts Store. Демонстраційний портфоліо-проєкт.' },
};

const ru: Dictionary = {
  nav: { catalog: 'Каталог', garage: 'Мой гараж', orders: 'Заказы', admin: 'Админ', login: 'Войти', cart: 'Корзина' },
  common: { viewAll: 'Смотреть все', addToCart: 'В корзину', inStock: 'В наличии', outOfStock: 'Нет в наличии', loading: 'Загрузка…', retry: 'Попробовать снова', save: 'Сохранить', cancel: 'Отмена', search: 'Поиск по названию, SKU или OEM', from: 'От' },
  hero: { eyebrow: 'Правильная деталь. С первого раза.', title: 'Создано для дороги впереди.', text: 'Запчасти OE-качества, точный подбор по авто и прозрачные цены — в одном магазине.', shop: 'Все запчасти', fitment: 'Подобрать для авто', stat1: 'деталей готовы к отправке', stat2: 'совместимость проверена', stat3: 'дней на возврат' },
  home: { categories: 'По системе автомобиля', categoriesText: 'Всё нужное для автомобиля — организовано так, как мыслит мастерская.', popular: 'Выбор мастеров', newest: 'Новые поступления', deals: 'Специальные предложения', benefits: 'Почему выбирают нас', precision: 'Точная совместимость', precisionText: 'Проверяем марку, модель, год и двигатель.', fast: 'Быстрая отправка', fastText: 'Товар в наличии отправляем за один рабочий день.', support: 'Живая экспертиза', supportText: 'Помогают специалисты по запчастям, а не скрипт.' },
  vehicle: { eyebrow: 'Подбор по авто', title: 'Какой у вас автомобиль?', make: 'Марка', model: 'Модель', year: 'Год', engine: 'Двигатель', choose: 'Выберите…', button: 'Показать совместимые детали' },
  catalog: { title: 'Каталог запчастей', text: 'Фильтруйте отборный ассортимент компонентов профессионального уровня.', filters: 'Фильтры', category: 'Категория', manufacturer: 'Производитель', price: 'Диапазон цен', available: 'Только в наличии', discount: 'Со скидкой', sort: 'Сортировка', popularity: 'Популярные', newest: 'Новые', priceAsc: 'Цена: по возрастанию', priceDesc: 'Цена: по убыванию', results: 'результатов', noResults: 'По этим фильтрам ничего не найдено.' },
  product: { sku: 'SKU', oem: 'OEM номер', fitment: 'Совместимые автомобили', specifications: 'Характеристики', quantity: 'Количество', related: 'Похожие товары', warranty: 'Гарантия 24 месяца', shipping: 'Отправка за 1 рабочий день' },
  auth: { loginTitle: 'С возвращением', registerTitle: 'Создайте аккаунт', email: 'Email', password: 'Пароль', firstName: 'Имя', lastName: 'Фамилия', signIn: 'Войти', register: 'Зарегистрироваться', noAccount: 'Впервые здесь?', haveAccount: 'Уже зарегистрированы?', logout: 'Выйти', error: 'Проверьте данные и попробуйте снова.' },
  cart: { title: 'Ваша корзина', empty: 'Корзина ждёт нужные детали.', subtotal: 'Сумма', discount: 'Скидка', shipping: 'Доставка', total: 'Итого', checkout: 'Перейти к оформлению', remove: 'Удалить', stockError: 'Количество превышает доступный запас.' },
  checkout: { title: 'Оформление', contact: 'Контактные данные', shipping: 'Адрес доставки', payment: 'Способ оплаты', summary: 'Ваш заказ', demo: 'ДЕМО-ОПЛАТА', demoText: 'Мы не собираем данные карты. Одобрение безопасно имитируется.', card: 'Демо-карта', cod: 'Оплата при получении', place: 'Создать демо-заказ', success: 'Заказ подтверждён', line1: 'Адрес', line2: 'Квартира / офис', city: 'Город', region: 'Область', postal: 'Почтовый индекс', country: 'Код страны', phone: 'Телефон' },
  account: { title: 'Личный кабинет', profile: 'Профиль', orders: 'История заказов', noOrders: 'Вы ещё не создавали заказы.' },
  admin: { title: 'Панель управления', users: 'Пользователи', products: 'Товары', orders: 'Заказы', revenue: 'Доход', recent: 'Последние заказы', lowStock: 'Малый запас', categories: 'Категории', manufacturers: 'Производители', vehicles: 'Автомобили', audit: 'Журнал аудита', access: 'Нужны права администратора' },
  status: { PENDING: 'Ожидает', CONFIRMED: 'Подтверждён', PROCESSING: 'Обрабатывается', SHIPPED: 'Отправлен', DELIVERED: 'Доставлен', CANCELLED: 'Отменён' },
  footer: { text: 'Детали, которые подходят. Поддержка, которая остаётся.', shop: 'Магазин', company: 'Компания', help: 'Помощь', rights: 'AutoParts Store. Демонстрационный портфолио-проект.' },
};

export const dictionaries: Record<Locale, Dictionary> = { en, uk, ru };

export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }
